"use client";

import { Check, ChevronRight, Compass, FileText, Folder, Hash, Mail, MessageCircle, Mic, Plus, Send, Square, Video } from "lucide-react";
import { useState } from "react";
import { LanguageScriptModule } from "@/components/ledger/LanguageScriptModule";
import { HeadingSwish } from "@/components/ledger/HeadingSwish";
import { usePersistentState } from "@/usePersistentState";
import { useSettings } from "@/SettingsContext";

export type UtilityContextId = "personal" | "work" | "email" | "developer" | "other";
export type UtilityStyleCategory = UtilityContextId;
export type UtilityStylePreferences = Partial<Record<UtilityStyleCategory, string>>;
type AppId = "telegram" | "messages" | "whatsapp" | "zoom" | "slack" | "gmail" | "mail" | "cursor" | "vscode" | "chatgpt" | "claude" | "sarvam" | "firefox" | "chrome" | "preview" | "finder";
type PreviewKind = "message" | "email" | "developer" | "note";
interface WritingStyle { id: string; name: string; description: string; transformed: string; }
interface UtilityContext { id: UtilityContextId; title: string; subtitle: string; raw: string; styles: WritingStyle[]; apps: { id: AppId; label: string }[]; preview: PreviewKind; }

const utilityContexts: UtilityContext[] = [
  { id: "personal", title: "personal messaging", subtitle: "the shared voice for personal apps — edit once, changes them all", preview: "message", raw: "hey for your information i do not know if the launch review can stay at three tomorrow because the user calls are still moving", styles: [{ id: "natural", name: "natural", description: "light cleanup, your voice kept", transformed: "Hey, just so you know, I’m not sure the launch review can stay at three tomorrow — the user calls are still moving." }, { id: "very-casual", name: "very casual", description: "lowercase, shorthand, zero fuss", transformed: "hey fyi not sure the launch review can stay at 3 tmrw, user calls are still moving" }, { id: "polished", name: "polished", description: "full punctuation and grammar", transformed: "Hi — I’m not sure we can keep tomorrow’s launch review at 3:00 PM, as the user calls are still shifting." }], apps: [{ id: "telegram", label: "Telegram" }, { id: "messages", label: "Messages" }, { id: "whatsapp", label: "WhatsApp" }] },
  { id: "work", title: "work messaging", subtitle: "the shared voice for work apps — edit once, changes them all", preview: "message", raw: "hey for your information i do not know if the launch review can stay at three tomorrow because the user calls are still moving", styles: [{ id: "clear", name: "clear", description: "clean sentences, shorthand kept", transformed: "Quick update: I’m not sure we can keep the launch review at 3 tomorrow. The user calls are still moving." }, { id: "casual", name: "casual", description: "lowercase workplace shorthand", transformed: "fyi, not sure launch review can stay at 3 tmrw — user calls are still moving" }, { id: "formal", name: "formal", description: "everything spelled out, properly", transformed: "For your awareness, I am not certain that we can retain the launch review at 3:00 PM tomorrow, as the user calls remain in flux." }], apps: [{ id: "zoom", label: "Zoom" }, { id: "slack", label: "Slack" }] },
  { id: "email", title: "email", subtitle: "the shared voice for email apps — edit once, changes them all", preview: "email", raw: "hey for your information i do not know if the launch review can stay at three tomorrow because the user calls are still moving", styles: [{ id: "professional", name: "professional", description: "conventional and to the point", transformed: "Hi team, I’m not sure we can keep tomorrow’s launch review at 3:00 PM because the user calls are still moving. I’ll confirm a revised time shortly." }, { id: "friendly", name: "friendly", description: "the same note, with warmth", transformed: "Hi team, a quick heads-up: the user calls are still moving, so I’m not sure we can hold tomorrow’s launch review at 3:00 PM. I’ll keep you posted." }, { id: "formal", name: "formal", description: "highest formality, full forms", transformed: "Dear team, I would like to note that we may need to reschedule tomorrow’s 3:00 PM launch review, as the user calls have not yet been finalized." }], apps: [{ id: "gmail", label: "Gmail" }, { id: "mail", label: "Mail" }] },
  { id: "developer", title: "developer", subtitle: "terse, and your code stays code", preview: "developer", raw: "make the capture service return routing confidence and keep every code identifier exactly as written", styles: [{ id: "clear", name: "clear", description: "direct instructions, logic preserved", transformed: "Add a routingConfidence field to the capture response. Preserve existing identifiers and return a typed result." }, { id: "concise", name: "concise", description: "minimal tokens, high-density prompts", transformed: "Add typed routingConfidence to capture response; preserve identifiers." }, { id: "structured", name: "structured", description: "markdown blocks, parameters highlighted", transformed: "## Task\nAdd `routingConfidence` to `CaptureResponse`.\n\n## Constraints\n- preserve identifiers\n- return typed result" }], apps: [{ id: "cursor", label: "Cursor" }, { id: "vscode", label: "VS Code" }, { id: "chatgpt", label: "ChatGPT" }, { id: "claude", label: "Claude" }, { id: "sarvam", label: "Sarvam AI" }] },
  { id: "other", title: "other apps", subtitle: "the shared default for everything else — edit once, changes them all", preview: "note", raw: "for everyone’s information, we are not sure if the launch review can stay at three tomorrow because the user calls are still moving", styles: [{ id: "balanced", name: "balanced", description: "cleaned, but still yours", transformed: "The launch review may need to move tomorrow; the user calls are still shifting." }, { id: "minimal", name: "minimal", description: "compressed to the essentials", transformed: "To do: Confirm the launch review time after the user calls." }, { id: "polished", name: "polished", description: "composed, complete sentences", transformed: "The launch review may need to be rescheduled tomorrow, as the user calls are still changing. Confirm a revised time once they are settled." }], apps: [{ id: "firefox", label: "Firefox" }, { id: "chrome", label: "Google Chrome" }, { id: "preview", label: "Preview" }, { id: "finder", label: "Finder" }], },
];

function WhatsAppMark() {
  return <svg viewBox="0 0 24 24" aria-label="WhatsApp"><path d="M20.5 11.7a8.5 8.5 0 0 1-12.6 7.5L3.5 20.5l1.3-4.2a8.5 8.5 0 1 1 15.7-4.6Z" /><path d="M9.4 7.8h1.1l.9 2.1-.8.9c.7 1.2 1.6 2.1 2.8 2.7l.9-.7 2 .9v1c-.4.4-1 .6-1.6.4-3.3-.8-5.9-3.4-6.6-6.6-.1-.6.1-1.1.5-1.6Z" /></svg>;
}

const appIconAssets: Partial<Record<AppId, string>> = {
  gmail: "https://cdn.simpleicons.org/gmail",
  firefox: "https://cdn.simpleicons.org/firefoxbrowser",
  chrome: "https://cdn.simpleicons.org/googlechrome",
  preview: "https://upload.wikimedia.org/wikipedia/en/d/d6/Preview_icon.png",
  finder: "https://upload.wikimedia.org/wikipedia/commons/b/b9/Finder_Icon_macOS_Tahoe.png",
};

function LinkedAppIcon({ id }: { id: AppId }) {
  const asset = appIconAssets[id];
  if (asset) return <span className="kivi-app-mark kivi-app-mark--asset" style={{ backgroundImage: `url(${asset})` }} />;
  if (id === "telegram") return <span className="kivi-app-mark kivi-app-mark--telegram"><Send size={14} fill="currentColor" /></span>;
  if (id === "messages") return <span className="kivi-app-mark kivi-app-mark--messages"><MessageCircle size={14} fill="currentColor" /></span>;
  if (id === "whatsapp") return <span className="kivi-app-mark kivi-app-mark--whatsapp"><WhatsAppMark /></span>;
  if (id === "zoom") return <span className="kivi-app-mark kivi-app-mark--zoom"><Video size={14} fill="currentColor" /></span>;
  if (id === "slack") return <span className="kivi-app-mark kivi-app-mark--slack"><Hash size={14} /></span>;
  if (id === "firefox" || id === "chrome") return <span className="kivi-app-mark kivi-app-mark--neutral"><Compass size={14} /></span>;
  if (id === "preview") return <span className="kivi-app-mark kivi-app-mark--neutral"><FileText size={14} /></span>;
  if (id === "finder") return <span className="kivi-app-mark kivi-app-mark--neutral"><Folder size={14} /></span>;
  return <span className="kivi-app-mark kivi-app-mark--mail"><Mail size={14} /></span>;
}

function StylePreview({ kind, raw, transformed }: { kind: PreviewKind; raw: string; transformed: string }) { if (kind === "email") return <span className="kivi-email-preview"><span className="kivi-email-preview__head"><b>To:</b> launch-team@kivi.ai</span><span className="kivi-email-preview__head"><b>Subject:</b> Tomorrow’s launch review</span><span className="kivi-email-preview__body">{transformed}</span><span className="kivi-email-preview__send">Send</span></span>; if (kind === "developer") return <span className="kivi-code-preview"><span className="kivi-code-preview__bar"><i /><i /><i /> terminal · kivi prompt</span><span><b>$</b> {raw}</span><pre>{transformed}</pre></span>; if (kind === "note") return <span className="kivi-note-preview"><span className="kivi-note-preview__bar">Notes <b>•••</b></span><strong>Untitled note</strong><span>{transformed}</span></span>; return <span className="kivi-style-preview"><span className="kivi-style-preview__app"><MessageCircle size={11} /> Messages <b>•••</b></span><span className="kivi-style-preview__raw">{raw}</span><span className="kivi-style-preview__result">{transformed}</span></span>; }

interface UtilityViewProps { onStartCapture: () => void; onStopCapture: () => void; phase: "idle" | "recording" | "processing" | "synthesized"; stylePreferences: UtilityStylePreferences; onStylePreferenceChange: (category: UtilityStyleCategory, styleId: string) => void; onContextChange: (context: UtilityContextId) => void; }
export function UtilityView({ onStartCapture, onStopCapture, phase, stylePreferences, onStylePreferenceChange, onContextChange }: UtilityViewProps) {
  const { captureShortcut } = useSettings();
  const [contextId, setContextId] = useState<UtilityContextId>("personal"); const [rulesByApp, setRulesByApp] = usePersistentState<Partial<Record<UtilityContextId, string>>>("kivi:styles:utility-rules-by-app", {}); const [savedAppId, setSavedAppId] = useState<UtilityContextId | null>(null); const [utilityTab, setUtilityTab] = useState<"styles" | "language">("styles");
  const context = utilityContexts.find((item) => item.id === contextId) ?? utilityContexts[0]; const selectedStyle = context.styles.find((style) => style.id === stylePreferences[context.id]) ?? context.styles[0];
  const rules = rulesByApp[context.id] ?? "";
  const switchContext = (id: UtilityContextId) => { setContextId(id); onContextChange(id); };
  return <section className="kivi-view kivi-view--utility">
    <header className="kivi-utility-style__top"><div className="kivi-unified-header-copy"><span className="kivi-eyebrow">Styles / Utility</span><h1 className="kivi-unified-title">{context.title}<span className="kivi-title-accent">.</span><HeadingSwish /></h1><p>{context.subtitle}</p></div><div className="kivi-view-header__actions"><small className="kivi-view-header__shortcut">{captureShortcut}</small><button type="button" className={`kivi-view-header__mic ${phase === "recording" ? "is-recording" : ""}`} onClick={phase === "recording" ? onStopCapture : onStartCapture} disabled={phase === "processing"} aria-label={phase === "recording" ? "Stop capture" : "Start capture"}>{phase === "recording" ? <Square size={12} fill="currentColor" /> : <Mic size={14} />}</button></div></header>
    <div className="kivi-utility-style__contexts" role="tablist" aria-label="Utility Styles">{utilityContexts.map((item) => <button key={item.id} type="button" role="tab" aria-selected={item.id === context.id} className={item.id === context.id ? "is-active" : ""} onClick={() => switchContext(item.id)}>{item.title}</button>)}</div>
    <div className="kivi-utility-toolbar" role="tablist"><button type="button" className={utilityTab === "styles" ? "is-active" : ""} onClick={() => setUtilityTab("styles")}>Writing styles</button><button type="button" className={utilityTab === "language" ? "is-active" : ""} onClick={() => setUtilityTab("language")}>How you sound, app by app</button></div>
    {utilityTab === "language" ? <LanguageScriptModule appId={context.id} /> : <>
    <article className="kivi-utility-style__panel"><span className="kivi-eyebrow">You say</span><p className="kivi-utility-style__raw">“{context.raw}”</p><div className="kivi-utility-style__heading"><div><span className="kivi-eyebrow">Writing style</span><h2>How Kivi should carry the thought</h2></div><small>applies to {context.apps.length} linked apps</small></div><div className="kivi-style-options" role="radiogroup" aria-label="Writing style">{context.styles.map((style) => <button type="button" key={style.id} role="radio" aria-checked={style.id === selectedStyle.id} className={style.id === selectedStyle.id ? "is-selected" : ""} onClick={() => onStylePreferenceChange(context.id, style.id)}><span className="kivi-style-options__choice"><i aria-hidden="true" /><strong>{style.name}</strong></span><small>{style.description}</small><StylePreview kind={context.preview} raw={context.raw} transformed={style.transformed} /></button>)}</div></article>
    <div className="kivi-utility-style__lower"><article className="kivi-custom-rules"><span className="kivi-eyebrow">Custom rules</span><textarea value={rules} onChange={(event) => { setRulesByApp((current) => ({ ...current, [context.id]: event.target.value })); setSavedAppId(null); }} placeholder="tell kivi exactly what to do — e.g. 'translate everything to English; keep every name in English'" /><button type="button" onClick={() => setSavedAppId(context.id)}>{savedAppId === context.id && <Check size={14} />}{savedAppId === context.id ? "saved" : "save note"}</button></article><article className="kivi-linked-apps"><div><span className="kivi-eyebrow">Linked apps</span><small>These apps share this style.</small></div>{context.apps.map((app) => <div className={context.id === "developer" ? "kivi-linked-apps__row is-text-only" : "kivi-linked-apps__row"} key={app.id}>{context.id !== "developer" && <LinkedAppIcon id={app.id} />}<strong>{app.label}</strong><ChevronRight size={14} aria-hidden="true" /></div>)}<button type="button" className="kivi-linked-apps__add" disabled title="Available in native Kivi"><Plus size={15} /> add app</button></article></div>
    </>}
  </section>;
}
